# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('court', models.CharField(max_length=100)),
                ('plaintiff', models.CharField(max_length=100)),
                ('defendant', models.CharField(max_length=100)),
                ('hashValue', models.CharField(max_length=100)),
                ('prevHashValue', models.CharField(max_length=100)),
                ('nonce', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Consenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict_type', models.CharField(choices=[('in', 'intermediate'), ('end', 'end')], max_length=20)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer', models.CharField(choices=[('pl', 'plaintiff'), ('df', 'defendant')], max_length=20)),
                ('view', models.CharField(max_length=1000)),
                ('statementOfFacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StatementOfFacts')),
            ],
        ),
        migrations.AddField(
            model_name='facts',
            name='statementOfFacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StatementOfFacts'),
        ),
        migrations.AddField(
            model_name='consenus',
            name='statementOfFacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StatementOfFacts'),
        ),
    ]
