# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170208_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='caseFile',
            field=models.CharField(default='ik bin ein Berliner', max_length=100),
            preserve_default=False,
        ),
    ]
