# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_case_casefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
